### ISSUE TITLE
Update RegisterOrganisation job

### ISSUE THREAD

**Issue by ilya-varchenya** [qaprosoft/jenkins-master#147] opened 2020-03-12 12:42 UTC
This ticket is dedicate for making work qps-pipelines without zafira integration

Update RegisterOrganisation job with new fields:
1. zafiraServiceURL
2. zafiraAccessTocken

Those fields must register into Jenkins Credentials

**Comment by vdelendik** [comment] 2020-04-05 13:48
@okamara, closing as dupe of the #150

**Closed by vdelendik** 2020-04-05 13:48 UTC
Labels: enhancement, qa-verified
